## 通过测试2025-10的新闻数据发现还是正收益的哦

In [81]:
import pandas as pd

# 读取目录：D:\workspace\xiaoyao\llm\batch_split_results下的industry_verdict_*.parquet
import os

# 定义目录路径
dir_path = "D:/workspace/xiaoyao/llm/batch_split_results"

# 列出目录下所有文件
files = os.listdir(dir_path)

# 筛选出所有industry_verdict_*.parquet文件
parquet_files = [f for f in files if f.startswith("industry_verdict_") and f.endswith(".parquet")]

# 读取每个文件并合并到一个DataFrame中
df_list = []
for parquet_file in parquet_files:
    file_path = os.path.join(dir_path, parquet_file)
    df = pd.read_parquet(file_path)
    df_list.append(df)

# 合并所有DataFrame
merged_df = pd.concat(df_list, ignore_index=True)

# 显示合并后的DataFrame信息
print(merged_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 509 entries, 0 to 508
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   analysis_id           509 non-null    object
 1   original_news_id      509 non-null    object
 2   original_news_date    509 non-null    object
 3   original_news_title   509 non-null    object
 4   industry              509 non-null    object
 5   impact_direction      509 non-null    object
 6   confidence_score      509 non-null    int64
 7   comprehensive_reason  509 non-null    object
 8   analysis_status       509 non-null    object
 9   error_msg             509 non-null    object
 10  log_path              509 non-null    object
 11  analysis_time         509 non-null    object
dtypes: int64(1), object(11)
memory usage: 47.8+ KB
None

In [82]:
# 获取merged_df里impact_direction为利好且confidence_score>7的记录
good_news_df = merged_df[(merged_df['impact_direction'] == '利好') & (merged_df['confidence_score'] > 8)]
good_news_df.head(3)

,analysis_id,original_news_id,original_news_date,original_news_title,industry,impact_direction,confidence_score,comprehensive_reason,analysis_status,error_msg,log_path,analysis_time
2,ana_d1d8f32b,114300,2025-01-01 00:00:00,《求是》杂志发表习近平总书记重要文章《以中国式现代化全面推进强国建设、民族复兴伟业》,光伏发电,利好,9,绿色低碳是现代化核心特征，光伏作为能源结构转型主引擎，政策支持明确且长期。行业洗牌后集中度提...,success,,debate_logs\news_news_single_20251011204846_21...,2025-10-11 20:49:27
3,ana_0468f820,114301,2025-01-01 00:00:00,坚定信心 挺膺担当 谱写中国式现代化崭新篇章——习近平主席二〇二五年新年贺词引发热烈反响,航天装备,利好,9,贺词明确肯定2024年航天成就，实为对重大工程落地的官方背书，强化后续项目延续性与订单确定性...,success,,debate_logs\news_news_single_20251011204927_09...,2025-10-11 20:50:12
17,ana_83fdbf9c,114307,2025-01-01 00:00:00,国内联播快讯,数字经济,利好,9,2023年数字经济核心产业增加值达12.76万亿元，其中应用软件与物联网占比超四成，政策落地...,success,,debate_logs\news_news_single_20251011205213_87...,2025-10-11 20:52:59

In [83]:
# 读取目录：D:\workspace\xiaoyao\llm\batch_split_results下的stock_recommendation_*.parquet

import os

# 定义目录路径
dir_path = "D:/workspace/xiaoyao/llm/batch_split_results"

# 列出目录下所有文件
files = os.listdir(dir_path)

# 筛选出所有industry_verdict_*.parquet文件
parquet_files = [f for f in files if f.startswith("stock_recommendation_") and f.endswith(".parquet")]

# 读取每个文件并合并到一个DataFrame中
df_list = []
for parquet_file in parquet_files:
    file_path = os.path.join(dir_path, parquet_file)
    df = pd.read_parquet(file_path)
    df_list.append(df)

# 合并所有DataFrame
merged_stock_df = pd.concat(df_list, ignore_index=True)

# 显示合并后的DataFrame信息
print(merged_stock_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 812 entries, 0 to 811
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   analysis_id            812 non-null    object
 1   stock_name             812 non-null    object
 2   stock_code             812 non-null    object
 3   recommendation_reason  812 non-null    object
 4   stock_rank             812 non-null    int64
dtypes: int64(1), object(4)
memory usage: 31.8+ KB
None

In [84]:
# 使用merged_df 和 merged_stock_df 进行合并
merged_df = pd.merge(merged_df, merged_stock_df, on=['analysis_id'], how='left')
merged_df = merged_df[merged_df['original_news_date'] <= '2025-01-02']

In [85]:
# 统计merged_df里stock_code的出现频次，倒序排序
df_recommendation_stock_code = merged_df['stock_code'].value_counts().sort_values(ascending=False)
# 转换为df，打印df_recommendation_stock_code
df_recommendation_stock_code = df_recommendation_stock_code.reset_index()
df_recommendation_stock_code.columns = ['stock_code', 'count']
df_recommendation_stock_code

   stock_code  count
0      000733      2
1      300274      2
2      002045      2
3      600879      2
4      002179      2
5      601186      1
6      601012      1
7      600388      1
8      300070      1
9      601390      1
10     002025      1
11     688981      1
12     000917      1
13     002371      1
14     600977      1
15     601888      1
16     002033      1
17     603888      1
18     603515      1
19     601766      1
20     601333      1
21     000768      1
22     002013      1
23     601598      1
24     603056      1
25     300251      1
26     601985      1
27     600875      1
28     600588      1
29     002202      1
30     300496      1
31     600026      1
32     600428      1
33     600803      1
34     600256      1
35     601808      1
36     300164      1
37     600406      1
38     000400      1
39     600089      1
40     600312      1
41     600138      1

In [86]:
# 统计merged_df里stock_code的出现频次，倒序排序
df_recommendation_industry = merged_df['industry'].value_counts().sort_values(ascending=False)
# 转换为df，打印df_recommendation_stock_code
df_recommendation_industry = df_recommendation_industry.reset_index()
df_recommendation_industry.columns = ['industry', 'count']
df_recommendation_industry

   industry  count
0      军工电子      5
1      航空装备      4
2    基建市政工程      2
3      光伏发电      2
4      环保设备      2
5    集成电路制造      2
6      电视广播      2
7      旅游综合      2
8      航天装备      2
9     输变电设备      2
10     油气开采      2
11     公路货运      2
12     铁路运输      2
13       核电      2
14    新能源发电      2
15      天然气      2
16     数字经济      2
17    电网自动化      2
18               1
19     文化传媒      1
20     灯光照明      1
21   影视动漫制作      1
22   石油石化贸易      1
23       航运      1
24     自然景点      1

In [87]:
# 读取D:\workspace\xiaoyao\data\widetable.parquet文件，筛选date在2025-10-08以后的数据
import pandas as pd

file_path = r'D:\workspace\xiaoyao\data\widetable.parquet'
df = pd.read_parquet(file_path)
df = df[df['date'] == '2025-01-03']

In [88]:

# 筛选出stock_code去除后缀后，仅获取前6位，在df_recommendation_stock_code['stock_code']中的数据
df = df[df['stock_code'].str[:6].isin(df_recommendation_stock_code['stock_code'])]
# 统计df的return_0d,return_1d的均值、众数，并打印屏幕
print(f"return_0d的均值为 {df['return_0d'].mean()}")
print(f"return_0d的众数为 {df['return_0d'].mode().values[0]}")
print(f"return_1d的均值为 {df['return_1d'].mean()}")
print(f"return_1d的众数为 {df['return_1d'].mode().values[0]}")

return_0d的均值为 -0.02053196718840235
return_0d的众数为 -0.0648298217179903
return_1d的均值为 -0.0253866132650895
return_1d的众数为 -0.11519815313582137

In [91]:

# 筛选出sw_l3_industry_name去除后缀后，删除所有的字母I，在df_recommendation_industry['industry']中的数据
df = df[df['sw_l3_industry_name'].str.replace('I', '').isin(df_recommendation_industry['industry'])]
# 统计df的return_0d,return_1d的均值、众数，并打印屏幕
print(f"return_0d的均值为 {df['return_0d'].mean()}")
print(f"return_0d的众数为 {df['return_0d'].mode().values[0]}")
print(f"return_1d的均值为 {df['return_1d'].mean()}")
print(f"return_1d的众数为 {df['return_1d'].mode().values[0]}")
print(f"return_1d的均值为 {df['return_3d'].mean()}")
print(f"return_1d的众数为 {df['return_3d'].mode().values[0]}")
df

return_0d的均值为 -0.02266363726017015
return_0d的众数为 -0.0648298217179903
return_1d的均值为 -0.026308726130598876
return_1d的众数为 -0.08572340340659783
return_1d的均值为 -0.020229559933119486
return_1d的众数为 -0.062148470222186704

,date,stock_code,open,close,low,high,volume,money,factor,high_limit,...,b4_p,b4_v,b5_p,b5_v,return_0d,return_1d,return_2d,return_3d,return_4d,return_5d
5187,2025-01-03,000400.XSHE,209.97,204.59,204.27,212.98,2022392.0,4.217658e+08,8.147808,230.91,...,25.71,900.0,25.70,1000.0,-0.025623,-0.019812,-0.024432,-0.006620,-0.017860,-0.033433
5372,2025-01-03,000733.XSHE,92.85,89.80,89.43,93.01,3229745.0,2.941189e+08,2.309099,101.23,...,40.00,200.0,39.99,300.0,-0.032849,-0.036618,-0.023156,-0.047281,-0.040065,-0.052235
5391,2025-01-03,000768.XSHE,225.65,218.09,217.92,227.80,3105615.0,6.905773e+08,8.596301,251.27,...,26.20,11000.0,26.19,100.0,-0.033503,-0.044183,-0.027033,-0.034257,0.017150,0.011832
5484,2025-01-03,000917.XSHE,55.53,51.93,51.53,56.16,6346404.0,3.379204e+08,7.989327,60.72,...,6.92,20900.0,6.91,25700.0,-0.064830,-0.076355,-0.059067,-0.048983,-0.041779,-0.082118
5658,2025-01-03,002025.XSHE,308.58,308.72,306.44,314.59,737743.0,2.295889e+08,6.679256,340.84,...,46.08,300.0,46.06,1000.0,0.000454,0.011472,0.031175,0.033994,0.067114,0.067114
5666,2025-01-03,002033.XSHE,54.04,50.93,50.81,54.28,4763121.0,2.483003e+08,5.977784,59.30,...,9.01,12000.0,9.00,7300.0,-0.057550,-0.054219,-0.047557,-0.054219,-0.069763,-0.097335
5804,2025-01-03,002179.XSHE,549.66,543.48,542.01,557.90,946686.0,5.194890e+08,14.712555,608.36,...,37.33,300.0,37.32,700.0,-0.011243,-0.026762,-0.008296,-0.022487,0.001346,0.007768
6839,2025-01-03,300251.XSHE,250.69,235.65,235.11,252.58,2632336.0,6.364452e+08,26.869682,299.60,...,9.29,6000.0,9.28,49800.0,-0.059994,-0.085723,-0.064303,-0.062148,-0.072879,-0.092146
7988,2025-01-03,600026.XSHG,21.25,21.62,21.12,22.42,24630969.0,5.351020e+08,1.860589,23.20,...,11.39,6200.0,11.35,700.0,0.017412,0.023529,0.014588,0.106824,0.045647,0.061176
8034,2025-01-03,600089.XSHG,694.36,686.51,683.70,701.66,616976.0,4.276015e+08,56.132945,763.41,...,12.34,100.0,12.33,5200.0,-0.011305,-0.010499,-0.008886,-0.018593,-0.022625,-0.032332
8205,2025-01-03,600312.XSHG,124.26,121.82,121.55,126.77,2482749.0,3.077524e+08,6.782862,135.66,...,18.20,2000.0,18.19,400.0,-0.019636,-0.023982,-0.030581,-0.015773,-0.040399,-0.071463
8266,2025-01-03,600388.XSHG,115.96,114.12,113.85,117.43,1297320.0,1.499256e+08,9.196087,127.27,...,12.57,20000.0,12.56,20500.0,-0.015868,-0.018972,-0.018972,-0.031735,-0.043636,-0.022163
8279,2025-01-03,600406.XSHG,1223.48,1208.79,1204.74,1238.17,395022.0,4.819077e+08,50.661745,1349.63,...,24.10,4800.0,24.08,26400.0,-0.012007,-0.014908,-0.016559,-0.022771,-0.018219,-0.028983
8293,2025-01-03,600428.XSHG,47.53,47.05,46.71,48.49,4710707.0,2.243273e+08,6.868447,52.27,...,6.89,2600.0,6.88,122100.0,-0.010099,-0.007153,-0.020198,-0.007153,-0.036188,-0.049232
8657,2025-01-03,600879.XSHG,321.69,312.78,307.96,322.80,1408052.0,4.428432e+08,37.103592,353.60,...,8.63,2000.0,8.62,1500.0,-0.027697,-0.026547,-0.019615,-0.041531,-0.029998,-0.046131
8714,2025-01-03,600977.XSHG,12.27,11.82,11.78,12.34,15871115.0,1.908736e+08,1.089799,13.49,...,11.22,200.0,11.21,2000.0,-0.036675,-0.052160,-0.059495,-0.056235,-0.066015,-0.083130
8800,2025-01-03,601186.XSHG,12.45,12.35,12.31,12.63,37439294.0,4.665818e+08,1.422719,13.76,...,8.72,32500.0,8.71,217500.0,-0.008032,-0.010442,-0.008032,-0.020884,-0.031325,-0.043373
8829,2025-01-03,601333.XSHG,4.55,4.51,4.51,4.62,39376763.0,1.795405e+08,1.371308,5.01,...,3.29,152200.0,3.28,129700.0,-0.008791,-0.002198,-0.010989,-0.015385,-0.028571,-0.050549
8839,2025-01-03,601390.XSHG,8.35,8.22,8.21,8.40,63736940.0,5.288712e+08,1.363926,9.15,...,6.09,5600.0,6.08,30600.0,-0.015569,-0.015569,-0.016766,-0.025150,-0.034731,-0.051497
10242,2025-01-03,688981.XSHG,90.10,88.31,87.53,91.13,61288981.0,5.452106e+09,1.000000,107.95,...,90.07,1759.0,90.06,200.0,-0.019867,-0.035072,0.005549,-0.014206,0.013541,0.034184